-- 단순하게 MAX를 사용하면 각 그룹의 가장 상위 레코드의 결과를 가져옴으로 올바른 결과x → 서브 쿼리를 사용해야 함.
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC;