# 2022-02 USER_ID = 1인 회원의 레코드가 2개 있어도 1개로 count 해야함.
SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH, B.GENDER, COUNT(DISTINCT(A.USER_ID)) AS USERS
FROM ONLINE_SALE AS A
INNER JOIN USER_INFO AS B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH, B.GENDER
HAVING B.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, B.GENDER;